export const CONDITIONS_CATALOG = [
    { id: 1, condicion: 'COVID-19' },
    { id: 2, condicion: 'Síntomas de COVID-19' },
    { id: 3, condicion: 'Dificultad visual' },
    { id: 4, condicion: 'Problemas auditivos' },
    { id: 5, condicion: 'Alergias' },
    { id: 6, condicion: 'Afecciones del corazón' },
    { id: 7, condicion: 'Epilepsia' },
    { id: 8, condicion: 'Asma' },
    { id: 9, condicion: 'Diabetes' },
    { id: 10, condicion: 'Hipertensión' },
    { id: 11, condicion: 'Problemas respiratorios' },
    { id: 12, condicion: 'Convulsiones' },
    { id: 13, condicion: 'Enfermedades de la sangre' },
    { id: 14, condicion: 'Hepatitis u otras enfermedades del hígado' },
    { id: 15, condicion: 'Limitaciones en actividad diaria' },
    { id: 16, condicion: 'Celiaquía' },
    { id: 17, condicion: 'Luxaciones' },
    { id: 18, condicion: 'Problemas de la columna' },
    { id: 19, condicion: 'Lesiones de cintura, rodillas o tobillos' },
    { id: 20, condicion: 'Lesiones de hombros o brazos' },
    { id: 21, condicion: 'Bajo cuidado médico' },
    { id: 22, condicion: 'Toma medicación actualmente' },
    { id: 23, condicion: 'Embarazo' },
    { id: 24, condicion: 'Otra condición que pueda perjudicar la salud' },
];
