INSERT INTO reportes_soap (
  paciente_nombre, 
  hora_incidente, 
  severity, 
  escena, 
  e_sintoma, 
  e_alergias, 
  e_medicacion, 
  e_historia_pasada, 
  e_ultima_ingesta, 
  e_eventos, 
  examen_fisico, 
  evaluacion_guia, 
  observaciones, 
  es_simulacro, 
  alumno_nombre, 
  signos_vitales, 
  notas_adicionales,
  viaje_id,
  user_id,
  created_at,
  updated_at
) VALUES (
  'Maria Garcia (Simulacro)',
  '14:20',
  'Alta',
  'Ubicación: Filo de la Virgen - Sector Norte. Escena segura, terreno rocoso y mojado. Víctima sentada consciente. Clima ventoso con descenso de temperatura.',
  'Dolor punzante e invalidante en tobillo derecho (9/10). Sensación de chasquido al caer. Parestesia leve en dedos del pie.',
  'Penicilina (reacción anafiláctica), Polen.',
  'Anticonceptivos orales (diario).',
  'Gastritis crónica leve, cirugía de meniscos en rodilla izquierda hace 2 años.',
  'Almuerzo liviano (sándwich y agua) hace 3 horas.',
  'La víctima descendía por acarreo suelto cuando su pie derecho se trabó entre dos bloques de granito, produciendo una rotación externa súbita seguida de caída lateral.',
  'Inspección: Edema perimaleolar masivo instantáneo, hematoma en cara lateral externa del tobillo. Deformidad evidente. Pulso pedio presente y simétrico. No se palpa crepitación ósea franca.',
  'Posible fractura de maleolo externo o esguince de tercer grado (ruptura de ligamento peroneo-astragalino).',
  'PLAN: 1. Inmovilización rígida con férula. 2. Control de inflamación (RICE). 3. Hidratación y abrigo. 4. Evacuación mediante camilla Kong.',
  true,
  'Mauricio Trekking',
  '[
    {"time": "14:30", "pulse": "98", "resp": "22", "bp": "130/85", "spo2": "96", "temp": "36.8", "avdi": "A", "skin": "Pálida/Fría"},
    {"time": "14:45", "pulse": "85", "resp": "18", "bp": "120/80", "spo2": "97", "temp": "36.6", "avdi": "A", "skin": "Rosada/Normal"},
    {"time": "15:00", "pulse": "72", "resp": "16", "bp": "115/75", "spo2": "98", "temp": "36.5", "avdi": "A", "skin": "Rosada/Seca"}
  ]',
  'Se dio aviso al centro de control a las 14:35. Se espera arribo de patrulla externa en 45 minutos. Paciente estable emocionalmente.',
  (SELECT id FROM viajes WHERE id IS NOT NULL LIMIT 1),
  (SELECT id FROM auth.users WHERE id IS NOT NULL LIMIT 1),
  NOW(),
  NOW()
);
